name: emoji_picker_flutter_example
description: Demonstrates how to use the emoji_picker_flutter plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.1.0


  tenor: ^1.0.9
  emoji_picker_flutter: ^1.0.5


flutter:
  uses-material-design: true